[tool.poetry]
name = "shared"
version = "1.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "~3.8.4"
requests = "^2.25.0"
tqdm = "^4.52.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
